### ISSUE TITLE
Edit the Description to make it more up to date.

### ISSUE THREAD

**Issue by xing1357** [AlexDev404/SquirrelOS#1]
I am rewriting SimpleOS, so please note on the description and README that it is the older version of SimpleOS. I might make a repo of SimpleOS-old just to let you know.

**Comment by AlexDev404** [comment]
Great to hear from the original author! 
How are you? I hope you're doing well. Pertaining to the readme, you must tell me when this new release of SimpleOS releases, as I will make sure to update my sources to it.
